name: CI

on:
  push:
    branches: '*'
  pull_request:
    branches: '*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4  # Обновили до последней версии

      - name: Set up JDK 17
        uses: actions/setup-java@v4  # Обновили до v4
        with:
          distribution: 'temurin'    # Явно указали дистрибутив Java
          java-version: '17'

      - name: Grant execute permission for gradlew
        run: chmod +x ./gradlew

      - name: Build with Gradle
        run: ./gradlew build

      - name: Upload Build Artifact
        if: success()  # Загружаем артефакт только если сборка успешна
        uses: actions/upload-artifact@v4
        with:
          name: app-debug.apk
          path: app/build/outputs/apk/debug/app-debug.apk
